// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace LastExit {

	using System;

	public delegate void IconReleasedHandler(object o, IconReleasedArgs args);

	public class IconReleasedArgs : GLib.SignalArgs {
		public LastExit.IconEntryPosition IconPosition{
			get {
				return (LastExit.IconEntryPosition) Args[0];
			}
		}

		public int Button{
			get {
				return (int) Args[1];
			}
		}

	}
}
