// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace LastExit {

	using System;

	public delegate void UrlActivatedHandler(object o, UrlActivatedArgs args);

	public class UrlActivatedArgs : GLib.SignalArgs {
		public string Url{
			get {
				return (string) Args[0];
			}
		}
	}
}
