// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace LastExit {

	using System;
	using System.Runtime.InteropServices;

	public enum IconEntryPosition {

		Primary,
		Secondary,
	}
}
